DROP TABLE IF EXISTS QUIZ;
  
CREATE TABLE QUIZ(
  QUIZID NUMBER(10) NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS QUESTION;
  
CREATE TABLE QUESTION(
  QUESTIONID NUMBER(10) NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  OPTIONS VARCHAR(250) NOT NULL,
  CORRECTOPTION VARCHAR(250) NOT NULL,
  QUIZID VARCHAR(250) NOT NULL,	
  POINTS NUMBER(10)NOT NULL,
  FOREIGN KEY (QUIZID) REFERENCES QUIZ(QUIZID)
);